// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"edgelink-api/internal/api"
	"edgelink-api/internal/infrastructure/cache"
	"edgelink-api/internal/infrastructure/db"
	"edgelink-api/internal/repo"
	"edgelink-api/internal/router"
	"edgelink-api/internal/svc"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"io"
)

// Injectors from wire.go:

func InitWebServer() *Container {
	gormDB := db.InitDB()
	cmdable := cache.InitRedisCache()
	iThingModelRepo := repo.NewThingModelRepo(gormDB, cmdable)
	iThingModelSvc := svc.NewThingModelSvc(iThingModelRepo)
	thingModelApi := api.NewThingModelApi(iThingModelSvc)
	v := router.LoadRegistryRouters(thingModelApi)
	engine := router.InitRouter(v)
	container := &Container{
		Engine:   engine,
		RedisCmd: cmdable,
		MysqlDB:  gormDB,
	}
	return container
}

// wire.go:

var (
	baseSet = wire.NewSet(db.InitDB, cache.InitRedisCache)
)

type Container struct {
	Engine   *gin.Engine
	RedisCmd redis.Cmdable
	MysqlDB  *gorm.DB
}

func (c *Container) Close() {
	if c.RedisCmd != nil {
		if r, ok := c.RedisCmd.(io.Closer); ok {
			_ = r.Close()
		}
	}

	if c.MysqlDB != nil {
		db2, err := c.MysqlDB.DB()
		if err == nil {
			_ = db2.Close()
		}
	}
}
