// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"edgelink-api/internal/api"
	"edgelink-api/internal/infrastructure/cache"
	"edgelink-api/internal/infrastructure/db"
	"edgelink-api/internal/pkg/logger"
	"edgelink-api/internal/repo"
	"edgelink-api/internal/router"
	"edgelink-api/internal/svc"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"io"
)

// Injectors from wire.go:

func InitWebServer() *Container {
	cmdable := cache.InitRedisCache()
	gormDB := db.InitDB()
	iThingModelRepo := repo.NewThingModelRepo(gormDB)
	iThingModelPropRepo := repo.NewThingModelPropRepo(gormDB)
	iProductRepo := repo.NewProductRepo(gormDB)
	iDeviceRepo := repo.NewDeviceRepo(gormDB)
	iThingModelSvc := svc.NewThingModelSvc(iThingModelRepo, iThingModelPropRepo, iProductRepo, iDeviceRepo)
	thingModelApi := api.NewThingModelApi(iThingModelSvc)
	iProductSvc := svc.NewProductSvc(iProductRepo, iThingModelRepo, iDeviceRepo)
	productApi := api.NewProductApi(iProductSvc)
	iDeviceSvc := svc.NewDeviceSvc(iDeviceRepo, iProductRepo, iThingModelPropRepo, cmdable)
	deviceApi := api.NewDeviceApi(iDeviceSvc)
	iHistoryDataRepo := repo.NewHistoryDataRepo(gormDB)
	iMetricSvc := svc.NewMetricSvc(iHistoryDataRepo)
	metricApi := api.NewMetricApi(iMetricSvc)
	iOAuthSvc := svc.NewOAuthSvc(cmdable)
	oAuthApi := api.NewOAuthApi(iOAuthSvc)
	v := router.LoadRegistryRouters(thingModelApi, productApi, deviceApi, metricApi, oAuthApi)
	engine := router.InitRouter(v, cmdable)
	container := &Container{
		Engine:   engine,
		RedisCmd: cmdable,
		MysqlDB:  gormDB,
	}
	return container
}

// wire.go:

var (
	baseSet = wire.NewSet(db.InitDB, cache.InitRedisCache)
)

type Container struct {
	Engine   *gin.Engine
	RedisCmd redis.Cmdable
	MysqlDB  *gorm.DB
}

func (c *Container) Close() {
	if c.RedisCmd != nil {
		if r, ok := c.RedisCmd.(io.Closer); ok {
			_ = r.Close()
			logger.Info("close redis completed")
		}
	}

	if c.MysqlDB != nil {
		db2, err := c.MysqlDB.DB()
		if err == nil {
			_ = db2.Close()
			logger.Info("close mysql completed")
		}
	}
}
