databases:
  edgelink:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    dbname: edgelink

redis:
  addr: "127.0.0.1:6379"
  password: "123456"
  db: 0

mqtt:
  host: 127.0.0.1
  port: 1883
  username: admin
  password: 123456