app:
  addr: ":8080"
  name: edgelink-api
  
databases:
  edgelink:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    dbname: edgelink

redis:
  addr: "127.0.0.1:6379"
  password: "123456"
  db: 0

mqtt:
  host: 127.0.0.1
  port: 1883
  username: admin
  password: 123456

oauth:
  clients:
    edgelink-ui:
      enabled: true
      # oauth2 服务端地址
      auth_base_url: "http://localhost:8080"
      client_id: "9fc70cfccebdedb75ff8fc2a181810f0"
      client_secret: "sk_8f0b5d02fdc4aef98b134ae47470f1c0"
      redirect_uri: "http://localhost:5000/oauth/callback"
      scopes:
        - basic
      timeout_seconds: 3
    edgelink-mobile:
      enabled: true
      # oauth2 服务端地址
      auth_base_url: "http://localhost:8080"
      client_id: "9fc70cfccebdedb75ff8fc2a181810f0"
      client_secret: "sk_8f0b5d02fdc4aef98b134ae47470f1c0"
      redirect_uri: "http://localhost:5173/oauth/callback"
      scopes:
        - basic
      timeout_seconds: 3
